name: tms_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  - asset/img/
  - asset/img/traffic-sign-svgrepo-com.svg

fonts:
  - family: Montserrat
    fonts:
      - asset: asset/fonts/Montserrat-ThinItalic.ttf
        style: italic
        weight: 100
      - asset: asset/fonts/Montserrat-Thin.ttf
        style: normal
        weight: 100
      - asset: asset/fonts/Montserrat-SemiBoldItalic.ttf
        style: italic
        weight: 800
      - asset: asset/fonts/Montserrat-SemiBold.ttf
        style: normal
        weight: 800
      - asset: asset/fonts/Montserrat-Regular.ttf
        style: normal
        weight: 400
      - asset: asset/fonts/Montserrat-MediumItalic.ttf
        style: italic
        weight: 500
      - asset: asset/fonts/Montserrat-Medium.ttf
        style: normal
        weight: 500
      - asset: asset/fonts/Montserrat-Italic.ttf
        style: normal
        weight: 400
      - asset: asset/fonts/Montserrat-ExtraBold.ttf
        style: normal
        weight: 900
      - asset: asset/fonts/Montserrat-BoldItalic.ttf
        style: italic
        weight: 900
      - asset: asset\fonts\Montserrat-Black.ttf
        style: italic
      - asset: asset\fonts\Montserrat-Black.ttf
        style: normal
